version: "3.9"
services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


