version: "3.9"
services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    ports:
      - "80:80"
    restart: always
    networks:
      - my-network
    volumes:
      - my-volume:/usr/local/tomcat/webapps/ 

volumes:
  my-volume:

networks:
  my-network:
    driver: bridge


